import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { server, db } from './browser-harness.mjs';
import { nativeOperation } from './native-bridge.mjs';
const require=createRequire(process.env.GAS_PLAYWRIGHT_MODULE ? import.meta.url : process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/' );
const { chromium }=require(process.env.GAS_PLAYWRIGHT_MODULE || 'playwright');
const op=(kind,data)=>nativeOperation('tmp/browser-test.db',{id:crypto.randomUUID(),kind,data});
let browser, page;
try {
 await op('DEBIT',{customerId:'customer',amountCents:4000,description:'Nota manual'});
 db.exec("UPDATE customer_account_entries SET created_at='2026-01-01' WHERE type='DEBIT'");
 await op('SALE',{saleType:'COUNTER',customerId:'customer',discountCents:0,items:[{productId:'gas',quantity:1}],payments:[{method:'CREDIT_CUSTOMER',amountCents:11000}]});
 await op('RECEIVE',{customerId:'customer',amountCents:12000,method:'PIX'});
 browser=await chromium.launch({executablePath:process.env.GAS_BROWSER_EXECUTABLE,headless:true,args:['--no-sandbox']});
 page=await browser.newPage({viewport:{width:1366,height:1000}});const errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error') errors.push(m.text());});
 await page.goto('http://127.0.0.1:1420/#/accounts/customer');
 await page.getByRole('button',{name:'Estornar',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Estornar recebimento',exact:true});
 await dialog.getByText(/Nota manual:/).waitFor();assert.equal(await dialog.locator('li').count(),2);
 assert.match(await dialog.innerText(),/120,00/);assert.match(await dialog.innerText(),/PIX/);
 await dialog.getByRole('button',{name:'Voltar sem estornar'}).click();assert.equal(db.prepare('SELECT COUNT(*) count FROM account_payment_refunds').get().count,0);
 await page.getByRole('button',{name:'Estornar',exact:true}).click();
 await dialog.getByLabel('Motivo do estorno').fill('Recebimento duplicado devolvido');
 await page.screenshot({path:'tmp/pdfs/estorno-recebimento.png'});
 await page.evaluate(()=>window.__loseRefundResponseOnce=true);
 await dialog.getByRole('button',{name:'Confirmar devolução'}).click();
 await dialog.getByRole('alert').filter({hasText:'Resposta interrompida após gravar estorno'}).waitFor();
 await dialog.getByRole('button',{name:'Confirmar devolução'}).click();
 await page.getByText('Recebimento estornado. Os débitos foram reabertos.',{exact:true}).waitFor();
 assert.equal(db.prepare('SELECT COUNT(*) count FROM account_payment_refunds').get().count,1);
 assert.equal(db.prepare('SELECT COUNT(*) count FROM account_payment_allocations').get().count,2);
 assert.equal(db.prepare("SELECT stock_quantity FROM products WHERE id='gas'").get().stock_quantity,9);
 await page.goto('http://127.0.0.1:1420/#/sales');page.once('dialog',d=>d.accept('Cliente devolveu o gás'));
 await page.getByRole('button',{name:'Cancelar',exact:true}).click();await page.getByText('Cancelada',{exact:true}).waitFor();
 assert.equal(db.prepare("SELECT stock_quantity FROM products WHERE id='gas'").get().stock_quantity,10);
 await page.goto('http://127.0.0.1:1420/#/accounts/customer');
 await page.getByLabel('Valor recebido').fill('40,00');await page.getByLabel('Forma de pagamento').selectOption('CASH');
 await page.getByRole('button',{name:'Registrar pagamento',exact:true}).click();await page.getByText('Pagamento registrado com sucesso.',{exact:true}).waitFor();
 await op('CASH_MOVE',{sessionId:'cash',type:'WITHDRAWAL',amountCents:14000});
 await page.getByRole('button',{name:'Estornar',exact:true}).click();await dialog.getByLabel('Motivo do estorno').fill('Correção de dinheiro');
 await dialog.getByRole('button',{name:'Confirmar devolução'}).click();await dialog.getByRole('alert').filter({hasText:'Saldo em dinheiro insuficiente'}).waitFor();
 assert.equal(db.prepare('SELECT COUNT(*) count FROM account_payment_refunds').get().count,1);
 await op('CASH_MOVE',{sessionId:'cash',type:'SUPPLY',amountCents:4000});
 await dialog.getByRole('button',{name:'Confirmar devolução'}).click();await dialog.waitFor({state:'hidden'});
 assert.equal(db.prepare('SELECT COUNT(*) count FROM account_payment_refunds').get().count,2);
 await page.waitForFunction(()=>document.querySelector('.account-balance-box strong')?.textContent.replace(/\s/g,'')==='R$40,00');
 assert.deepEqual(errors,[]);console.log('PASS: full multi-debt refund, confirmation/cancel, lost response retry, sale cancellation, cash balance protection; real Rust backend, no console errors');
} catch(error) {console.error(await page?.locator('body').innerText());throw error;} finally {await browser?.close();await server.close();}
