import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { server, db } from './browser-harness.mjs';
const require=createRequire(process.env.GAS_PLAYWRIGHT_MODULE ? import.meta.url : process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/' : import.meta.url);
const { chromium }=require(process.env.GAS_PLAYWRIGHT_MODULE || 'playwright');
let browser; let page;
try {
 browser=await chromium.launch({executablePath:process.env.GAS_BROWSER_EXECUTABLE,headless:true,args:['--no-sandbox']});
 page=await browser.newPage({viewport:{width:1366,height:900}});const errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error') errors.push(m.text());});
 await page.goto('http://127.0.0.1:1420/#/sales/new');
 await page.getByRole('button',{name:/Gás P13/}).click();
 await page.getByLabel('Pagamento misto').check();
 await page.getByLabel('Dinheiro — parcela').fill('50.00');
 await page.getByLabel('PIX — parcela').fill('60,00');
 await page.getByLabel(/Valor recebido/).fill('100,00');
 await page.getByRole('button',{name:'Finalizar venda',exact:true}).click();
 await page.getByRole('dialog').waitFor();
 assert.equal(db.prepare('SELECT total_cents FROM sales').get().total_cents,11000);
 assert.equal(db.prepare("SELECT amount_cents FROM payments WHERE method='PIX'").get().amount_cents,6000);
 assert.equal(db.prepare("SELECT change_cents FROM payments WHERE method='CASH'").get().change_cents,5000);
 await page.getByRole('button',{name:'Fechar comprovante',exact:true}).click();
 await page.getByRole('link',{name:'Produtos',exact:true}).click();
 await page.getByRole('row').filter({hasText:'Gás P13'}).getByRole('link',{name:'Editar',exact:true}).click();
 await page.getByLabel(/Nome do produto/).fill('Gás P13 revisado');
 await page.getByLabel('Preço Portaria').fill('115.50');
 await page.getByLabel('Nova categoria').fill('Combustíveis');
 await page.getByRole('button',{name:'Cadastrar categoria'}).click();
 await page.getByLabel('Nova categoria').waitFor({state:'visible'});
 await page.waitForFunction(()=>document.querySelector('select')?.selectedOptions[0]?.textContent==='Combustíveis');
 await page.getByRole('button',{name:'Salvar produto'}).click();
 await page.getByText('Gás P13 revisado',{exact:true}).waitFor();
 assert.equal(db.prepare("SELECT counter_price_cents FROM products WHERE id='gas'").get().counter_price_cents,11550);
 await page.getByRole('link',{name:'Estoque',exact:true}).click();
 await page.getByRole('button',{name:/Gás P13 revisado/}).click();
 await page.getByRole('button',{name:'Devolução',exact:true}).click();
 await page.getByLabel('Quantidade',{exact:true}).fill('1');
 await page.getByLabel('Motivo / observação').fill('Produto retornou fisicamente');
 await page.getByRole('button',{name:'Registrar movimentação'}).click();
 await page.getByText('Estoque atualizado: 9 → 10',{exact:true}).waitFor();
 assert.equal(db.prepare("SELECT stock_quantity FROM products WHERE id='gas'").get().stock_quantity,10);
 await page.goto('http://127.0.0.1:1420/#/accounts/customer');
 await page.locator('form').first().getByLabel(/^Valor/).fill('100,00');
 await page.getByLabel('Descrição',{exact:true}).fill('Nota manual');
 await page.getByLabel('Vencimento',{exact:true}).fill('2026-12-01');
 await page.getByRole('button',{name:'Adicionar débito'}).click();
 await page.getByText('Lançamento adicionado.',{exact:true}).waitFor();
 await page.getByLabel(/Valor recebido/).fill('40.00');
 await page.evaluate(()=>window.__losePaymentResponseOnce=true);
 await page.getByRole('button',{name:'Registrar pagamento',exact:true}).click();
 await page.getByText('Resposta interrompida após gravar recebimento',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Registrar pagamento',exact:true}).click();
 await page.getByRole('cell',{name:'Parcial',exact:true}).waitFor();
 assert.equal(db.prepare("SELECT COUNT(*) count FROM customer_account_entries WHERE type='PAYMENT'").get().count,1);
 await page.getByLabel(/Valor recebido/).fill('60,00');
 await page.getByRole('button',{name:'Registrar pagamento',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.account-balance-box strong')?.textContent.replace(/\s/g,'') === 'R$0,00');
 assert.equal(db.prepare("SELECT status FROM customer_account_entries WHERE type='DEBIT'").get().status,'PAID');
 await page.getByRole('link',{name:'Início',exact:true}).click();
 await page.getByText('R$ 110,00',{exact:true}).waitFor();
 await page.screenshot({path:'tmp/pdfs/revisao-dashboard.png'});
 assert.deepEqual(errors,[]);console.log('PASS: mixed payment, change, category/product edit, stock return, partial payment, settlement, live dashboard; no console errors');
} catch(error) { console.error(await page?.locator("body").innerText()); throw error; } finally { await browser?.close(); await server.close(); }
